$(document).ready(function(){
    $('#hero-slider').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        items:1,
        smartSpeed:1000,
        autoplay:true,
        autoplayTimeout:5000,
        autoplayHoverPause:false,
        dots:false,
        responsive:{
            0:{
                nav:false
            },
            600:{
                nav:true
            }
        }
    });
    $('#project-slider').owlCarousel({
        loop:true,
        margin:10,
        nav:true,
        smartSpeed:1000,
        dots:false,
        margin:20,
        responsive:{
            0:{
                items:1,
                margin:0,
                nav:false,
                dots:true
            },
            768:{
               items:2,
               nav:false,
               dots:true
            },
            1140:{
                items:2,
                nav:false,
                dots:true,
                center:true,
            }
        }
    });
    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:10,
        nav:false,
        dots:true,
        items:1
        
    });
})